Now uses 'conky-sessionfile'

diff --git a/bl-conky-session b/bl-conky-session
--- a/bl-conky-session
+++ b/bl-conky-session
@@ -6,7 +6,7 @@
 #
 ########################################################################
 CONKYPATH="$HOME/.conky"
-SESSIONFILE="$CONKYPATH/conky-session"
+SESSIONFILE="$CONKYPATH/conky-sessionfile"
 USAGE=$(echo -e "\vUSAGE:\tbl-conky-session [OPTION(S)]...FILES"
          echo -e "\n\tWith no command argument, the script uses the default"
          echo -e "\t\"\$CONKYPATH/conky-session\" sessionfile"
@@ -37,8 +37,9 @@ findArgs(){     # get command args (switches & sessionfile paths)
             rawArr[$i]="$arg"       # add sessionfiles to array
             i=$(($i+1))
         else
-            echo "ERROR: sessionfile \"$arg\" not found" >&2
-            exit 1
+            echo -e "ERROR: sessionfile \"$arg\" not found. Using default" >&2
+            conky -q 
+            exit 0
         fi
     done
     # remove duplicate args
