Improved command arg checking; updated usage

diff --git a/bl-tint2-session b/bl-tint2-session
--- a/bl-tint2-session
+++ b/bl-tint2-session
@@ -6,25 +6,28 @@
 #
 ########################################################################
 TINT2PATH="$HOME/.config/tint2"
+SESSIONFILE="$TINT2PATH/tint2-session"
+USAGE=$(
+    echo -e "\vUSAGE:  with no command argument, the script uses the default"
+    echo -e "\tTint2 session file \"$TINT2PATH/tint2-session.txt\""
+    echo -e "\v\tTo start them at login, add the following line to autostart:"
+    echo -e "\v\t\t\"(sleep 2s && tint2-session) &\""
+)
 
 if [ $# -eq 0 ];then
-    SESSIONFILE="$TINT2PATH/tint2-session.txt"
+    if test -f "$1";then
+        source $SESSIONFILE
+    else
+        echo -e "\v\tERROR: SESSIONFILE \"$SESSIONFILE\" not found!" >&2
+        echo "$USAGE"
+        exit 1
+    fi
 elif [[ $1 = "-h" ]] || [[ $1 = "--help" ]];then
-    echo "  USAGE: with no command argument, the script uses the default"
-    echo "  Tint2 session file '$TINT2PATH/tint2-session.txt'"
-    echo
-    echo "  To run other session files use 'bl-tint2-session /path/to/file'"
-    echo
+    echo "$USAGE"
     exit 0
 else
-    SESSIONFILE="$1"
-fi
-
-if [ -e "$SESSIONFILE" ];then
-   source $SESSIONFILE
-else
-    echo $"ERROR: $SESSIONFILE not found" >&2
-    exit 1
+    echo -e "\v\tWrong input!"
+    echo -e "\v\tUse \"bl-tint2-session [-h|--help]\"\v"
 fi
 
 exit 0
